name: farmer_iot_sensors
description: "AgroIntelX - Smart Farming IoT Dashboard"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/agrointelx_logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
